export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
};
